### ISSUE TITLE
Backend Serving Wrong Page

### ISSUE THREAD

**Issue by crosenblatt** [JMKassman/hello-mentors-server#42]
For the password reset page, the file is called change-password, not reset-password and this is causing issues with the link

**Comment by JMKassman** [comment]
No its not...
![image](https://user-images.githubusercontent.com/7897446/56232628-38044e80-604f-11e9-9dad-5e48c40018c4.png)

**Comment by crosenblatt** [comment]
It was originally called change-password. I changed it. Is it possible the online server still has that file?
